# Generated by Django 3.0.5 on 2020-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_auto_20200504_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('Dept', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='institute_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
