# Generated by Django 3.0.5 on 2020-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_auto_20200505_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_email',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
