# Generated by Django 3.0.5 on 2020-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_admin_admin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
