# Generated by Django 3.0.5 on 2020-06-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doct_name', models.CharField(max_length=100)),
                ('doct_id', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
