# Generated by Django 3.0.5 on 2020-05-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='Qr',
            new_name='Student',
        ),
    ]
