# Generated by Django 3.0.5 on 2020-06-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable', models.CharField(max_length=1000)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.Branches')),
            ],
        ),
    ]
