# Generated by Django 3.0.5 on 2020-06-29 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.Login'),
        ),
    ]
